-- V1__init.sql
-- Initial schema for the Policy Management API.
-- Mirrors the JPA entities: AppUser -> users, Client -> clients, Policy -> policies.
-- Order matters: users before clients (FK), clients before policies (FK).

-- ───────────────────────────── users ─────────────────────────────
CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL
);

-- ──────────────────────────── clients ────────────────────────────
CREATE TABLE clients (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255),
    last_name VARCHAR(255),
    email     VARCHAR(255),
    phone     VARCHAR(255),
    user_id   BIGINT NOT NULL,
    CONSTRAINT fk_clients_owner FOREIGN KEY (user_id) REFERENCES users (id)
);

-- ──────────────────────────── policies ───────────────────────────
CREATE TABLE policies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_make  VARCHAR(255),
    vehicle_model VARCHAR(255),
    vehicle_year  INTEGER,
    vin           VARCHAR(255),
    license_plate VARCHAR(255),
    status        VARCHAR(255),
    policy_number VARCHAR(255),
    premium       DOUBLE PRECISION,
    start_date    TIMESTAMP,
    end_date      TIMESTAMP,
    client_id     BIGINT,
    CONSTRAINT fk_policies_client FOREIGN KEY (client_id) REFERENCES clients (id)
);
